add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[\\$](bold blue) "
error_symbol = "[\\$](bold red) "
vicmd_symbol = "[\\$](bold yellow) "

[nodejs]
disabled = true

[python]
disabled = true

[directory]
truncate_to_repo = false
style = "bold blue"

[package]
disabled = true
